---
title: "git_00"
author: "Kim Godfrey"
date: "Spring semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

You are old, Father William," the young man said,  
    "And your hair has become very white;  
And yet you incessantly stand on your head—  
    Do you think, at your age, it is right?"  

    

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done--  
"It's very rude of him," she said,  
"To come and spoil the fun!"  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

You may write me down in history  
With your bitter, twisted lies,  
You may trod me in the very dirt  
But still, like dust, I'll rise.  

Does my sassiness upset you?  
Why are you beset with gloom?  
’Cause I walk like I've got oil wells  
Pumping in my living room.  

Just like moons and like suns,  
With the certainty of tides,  
Just like hopes springing high,  
Still I'll rise.

Did you want to see me broken?  
Bowed head and lowered eyes?  
Shoulders falling down like teardrops,  
Weakened by my soulful cries?  

Does my haughtiness offend you?  
Don't you take it awful hard  
’Cause I laugh like I've got gold mines  
Diggin’ in my own backyard.  

You may shoot me with your words,  
You may cut me with your eyes,  
You may kill me with your hatefulness,  
But still, like air, I’ll rise.  

Does my sexiness upset you?  
Does it come as a surprise  
That I dance like I've got diamonds  
At the meeting of my thighs?  

Out of the huts of history’s shame  
I rise  
Up from a past that’s rooted in pain  
I rise  
I'm a black ocean, leaping and wide,  
Welling and swelling I bear in the tide.  

Leaving behind nights of terror and fear  
I rise  
Into a daybreak that’s wondrously clear  
I rise 
Bringing the gifts that my ancestors gave,  
I am the dream and the hope of the slave.  
I rise  
I rise  
I rise.  






























